[book]
authors = ["0xTitan"]
language = "en"
multilingual = false
src = "src"
[output.html.fold]
enable = true    # whether or not to enable section folding
level = 0         # the depth to start folding
